/* Generated by Yosys 0.52 (git sha1 fee39a3284c90249e1d9684cf6944ffbbcbb8f90) */

(* top =  1  *)
(* src = "half_adder.sv:1.1-13.10" *)
module half_adder(a, b, sum, carry);
  (* src = "half_adder.sv:3.18-3.19" *)
  input a;
  wire a;
  (* src = "half_adder.sv:4.18-4.19" *)
  input b;
  wire b;
  (* src = "half_adder.sv:6.18-6.23" *)
  output carry;
  wire carry;
  (* src = "half_adder.sv:5.18-5.21" *)
  output sum;
  wire sum;
  assign sum = b ^ a;
  assign carry = b & a;
endmodule
